server:
  port: 5678
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.bsp.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/bsp/"
  application:
    name: BSP Cron Trigger

azure:
  application-insights:
    instrumentation-key: ${bsp.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
