server:
  port: 5678
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.bsp.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/bulk-scan/"
  application:
    name: BSP Cron Trigger

app:
  trigger-type: ${TRIGGER_TYPE}
  enabled: ${TRIGGER_ENABLED}

authorisation:
  bearer-token: ${ACTIONS_API_KEY:moshkupo}

url:
  send-letter-service: ${SEND_LETTER_SERVICE_URL:http://localhost:8485}
  blob-router-service: ${BLOB_ROUTER_SERVICE_URL:http://localhost:8584}
  bulk-scan-processor: ${BULK_SCAN_PROCESSOR_URL:http://localhost:8581}
  bulk-scan-orchestrator: ${BULK_SCAN_ORCHESTRATOR_URL:http://localhost:8582}

slack:
  token-daily-checks: ${SLACK_TOKEN_DAILY_CHECKS:atoken}
  channel-id-daily-checks: ${SLACK_CHANNEL_TOKEN_DAILY_CHECKS:atoken}
