server:
  port: 5678
  shutdown: "graceful"

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.bsp.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/bulk-scan/"
  application:
    name: BSP Cron Trigger

app:
  trigger-type: ${TRIGGER_TYPE}

url:
  send-letter-service: ${SEND_LETTER_SERVICE_URL}

slack:
  token-daily-checks: ${SLACK_TOKEN_DAILY_CHECKS}
  channel-id-daily-checks: ${SLACK_CHANNEL_TOKEN_DAILY_CHECKS}
