job:
  image: 'hmctspublic.azurecr.io/bulk-scan/cron-trigger:latest'
  aadIdentityName: bsp
  keyVaults:
    bulk-scan:
      secrets:
        - name: slack-token-bsp
          alias: slack-token-bsp
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  global:
    jobKind: CronJob
    enableKeyVaults: true
